### ISSUE TITLE
Remove this package?

### ISSUE THREAD

**Issue by gforcada** [plone/plone.bbb_testing#1]
There's no code on it, but I'm not sure if there is a reason for it to be around... /me wonders

**Comment by gotcha** [comment]
For information, those were created when we wanted to add bbb code to plone.testing and plone.app.testing.
At that time, we were told to put our code outside plone.testing and p.a.testing.

This lead to another team recreating our work as they had no idea that we had started the work.

Another example of stop energy when perfection discourages people to contribute

**Comment by gotcha** [comment]
iow, yes, this can be removed.
